export const phrases = {
  select:    ['Go for it!', 'Good luck!'],
  correct:   ['¡Felicitaciones!', '¡Enhorabuena!'],
  incorrect: ['Lo siento', 'Perdón', 'No exactamente'],
  try:       ['otra vez!', 'vuelve a intentarlo!', 'try again!']
}

export const lastCard = {
  front: 'Congrats!', back: '', options: ['Restart', 'Restart', 'Restart', 'Restart']
}

export const flashcards = [
  { front: 'Apple', back: 'Manzana', options: ['Naranja', 'Manzana', 'Fresa', 'Sandía'] },
  { front: 'Banana', back: 'Plátano', options: ['Limón', 'Uvas', 'Plátano', 'Manzana'] },
  { front: 'Orange', back: 'Naranja', options: ['Fresa', 'Sandía', 'Limón', 'Naranja'] },
  { front: 'Strawberry', back: 'Fresa', options: ['Plátano', 'Fresa', 'Manzana', 'Uvas'] },
  { front: 'Watermelon', back: 'Sandía', options: ['Piña', 'Uvas', 'Sandía', 'Pera'] },
  { front: 'Lemon', back: 'Limón', options: ['Limón', 'Naranja', 'Cereza', 'Coco'] },
  { front: 'Grapes', back: 'Uvas', options: ['Fresa', 'Pera', 'Melocotón', 'Uvas'] },
  { front: 'Pear', back: 'Pera', options: ['Manzana', 'Pera', 'Piña', 'Mango'] },
  { front: 'Peach', back: 'Melocotón', options: ['Cereza', 'Limón', 'Melocotón', 'Sandía'] },
  { front: 'Pineapple', back: 'Piña', options: ['Piña', 'Coco', 'Plátano', 'Pera'] },
  { front: 'Cherry', back: 'Cereza', options: ['Uvas', 'Naranja', 'Mango', 'Cereza'] },
  { front: 'Mango', back: 'Mango', options: ['Melocotón', 'Mango', 'Fresa', 'Limón'] },
  { front: 'Coconut', back: 'Coco', options: ['Coco', 'Piña', 'Sandía', 'Manzana'] },
  { front: 'Avocado', back: 'Aguacate', options: ['Pepino', 'Pera', 'Aguacate', 'Lechuga'] },
  { front: 'Tomato', back: 'Tomate', options: ['Pimiento', 'Tomate', 'Patata', 'Cebolla'] },
  { front: 'Potato', back: 'Patata', options: ['Zanahoria', 'Ajo', 'Pepino', 'Patata'] },
  { front: 'Onion', back: 'Cebolla', options: ['Cebolla', 'Lechuga', 'Maíz', 'Tomate'] },
  { front: 'Garlic', back: 'Ajo', options: ['Patata', 'Ajo', 'Pimiento', 'Champiñón'] },
  { front: 'Carrot', back: 'Zanahoria', options: ['Pepino', 'Cebolla', 'Zanahoria', 'Lechuga'] },
  { front: 'Lettuce', back: 'Lechuga', options: ['Tomate', 'Maíz', 'Ajo', 'Lechuga'] },
  { front: 'Cucumber', back: 'Pepino', options: ['Pepino', 'Pimiento', 'Zanahoria', 'Patata'] },
  { front: 'Pepper', back: 'Pimiento', options: ['Cebolla', 'Pimiento', 'Tomate', 'Champiñón'] },
  { front: 'Mushroom', back: 'Champiñón', options: ['Maíz', 'Lechuga', 'Champiñón', 'Ajo'] },
  { front: 'Corn', back: 'Maíz', options: ['Patata', 'Pepino', 'Cebolla', 'Maíz'] },
  { front: 'Beans', back: 'Frijoles', options: ['Arroz', 'Frijoles', 'Pan', 'Queso'] },
  { front: 'Rice', back: 'Arroz', options: ['Arroz', 'Pan', 'Frijoles', 'Huevo'] },
  { front: 'Bread', back: 'Pan', options: ['Queso', 'Leche', 'Pan', 'Mantequilla'] },
  { front: 'Cheese', back: 'Queso', options: ['Pan', 'Huevo', 'Mantequilla', 'Queso'] },
  { front: 'Milk', back: 'Leche', options: ['Leche', 'Agua', 'Café', 'Jugo'] },
  { front: 'Butter', back: 'Mantequilla', options: ['Queso', 'Mantequilla', 'Leche', 'Azúcar'] },
  { front: 'Egg', back: 'Huevo', options: ['Pan', 'Arroz', 'Huevo', 'Pollo'] },
  { front: 'Chicken', back: 'Pollo', options: ['Cerdo', 'Pescado', 'Carne de res', 'Pollo'] },
  { front: 'Beef', back: 'Carne de res', options: ['Carne de res', 'Pollo', 'Pescado', 'Cerdo'] },
  { front: 'Fish', back: 'Pescado', options: ['Cerdo', 'Pescado', 'Pollo', 'Huevo'] },
  { front: 'Pork', back: 'Cerdo', options: ['Pescado', 'Carne de res', 'Cerdo', 'Pollo'] },
  { front: 'Salt', back: 'Sal', options: ['Azúcar', 'Agua', 'Café', 'Sal'] },
  { front: 'Sugar', back: 'Azúcar', options: ['Azúcar', 'Sal', 'Mantequilla', 'Leche'] },
  { front: 'Water', back: 'Agua', options: ['Jugo', 'Agua', 'Té', 'Café'] },
  { front: 'Coffee', back: 'Café', options: ['Leche', 'Té', 'Café', 'Jugo'] },
  { front: 'Tea', back: 'Té', options: ['Agua', 'Café', 'Jugo', 'Té'] },
  { front: 'Juice', back: 'Jugo', options: ['Jugo', 'Leche', 'Agua', 'Té'] },
  { front: 'Breakfast', back: 'Desayuno', options: ['Cena', 'Desayuno', 'Almuerzo', 'Cocina'] },
  { front: 'Lunch', back: 'Almuerzo', options: ['Desayuno', 'Cena', 'Almuerzo', 'Mesa'] },
  { front: 'Dinner', back: 'Cena', options: ['Almuerzo', 'Desayuno', 'Cocina', 'Cena'] },
  { front: 'Kitchen', back: 'Cocina', options: ['Cocina', 'Dormitorio', 'Baño', 'Casa'] },
  { front: 'Table', back: 'Mesa', options: ['Silla', 'Mesa', 'Puerta', 'Ventana'] },
  { front: 'Chair', back: 'Silla', options: ['Mesa', 'Ventana', 'Silla', 'Casa'] },
  { front: 'Plate', back: 'Plato', options: ['Taza', 'Tenedor', 'Cuchara', 'Plato'] },
  { front: 'Cup', back: 'Taza', options: ['Taza', 'Botella', 'Plato', 'Servilleta'] },
  { front: 'Fork', back: 'Tenedor', options: ['Cuchillo', 'Tenedor', 'Cuchara', 'Plato'] },
  { front: 'Knife', back: 'Cuchillo', options: ['Tenedor', 'Cuchara', 'Cuchillo', 'Servilleta'] },
  { front: 'Spoon', back: 'Cuchara', options: ['Plato', 'Taza', 'Tenedor', 'Cuchara'] },
  { front: 'Napkin', back: 'Servilleta', options: ['Servilleta', 'Botella', 'Cuchillo', 'Taza'] },
  { front: 'Bottle', back: 'Botella', options: ['Taza', 'Botella', 'Plato', 'Cuchara'] },
  { front: 'House', back: 'Casa', options: ['Puerta', 'Ventana', 'Casa', 'Escuela'] },
  { front: 'Door', back: 'Puerta', options: ['Casa', 'Ventana', 'Dormitorio', 'Puerta'] },
  { front: 'Window', back: 'Ventana', options: ['Ventana', 'Puerta', 'Mesa', 'Silla'] },
  { front: 'Bedroom', back: 'Dormitorio', options: ['Baño', 'Dormitorio', 'Cocina', 'Casa'] },
  { front: 'Bathroom', back: 'Baño', options: ['Cocina', 'Casa', 'Baño', 'Dormitorio'] },
  { front: 'School', back: 'Escuela', options: ['Tienda', 'Ciudad', 'Calle', 'Escuela'] },
  { front: 'Book', back: 'Libro', options: ['Libro', 'Papel', 'Lápiz', 'Escuela'] },
  { front: 'Pencil', back: 'Lápiz', options: ['Papel', 'Lápiz', 'Libro', 'Mesa'] },
  { front: 'Paper', back: 'Papel', options: ['Libro', 'Escuela', 'Papel', 'Lápiz'] },
  { front: 'Teacher', back: 'Profesor', options: ['Estudiante', 'Amigo', 'Padre', 'Profesor'] },
  { front: 'Student', back: 'Estudiante', options: ['Estudiante', 'Profesor', 'Niño', 'Amigo'] },
  { front: 'Friend', back: 'Amigo', options: ['Hermano', 'Amigo', 'Padre', 'Estudiante'] },
  { front: 'Family', back: 'Familia', options: ['Madre', 'Hermana', 'Familia', 'Amigo'] },
  { front: 'Mother', back: 'Madre', options: ['Padre', 'Hermana', 'Familia', 'Madre'] },
  { front: 'Father', back: 'Padre', options: ['Padre', 'Hermano', 'Madre', 'Niño'] },
  { front: 'Brother', back: 'Hermano', options: ['Hermana', 'Hermano', 'Amigo', 'Padre'] },
  { front: 'Sister', back: 'Hermana', options: ['Madre', 'Familia', 'Hermana', 'Hermano'] },
  { front: 'Child', back: 'Niño', options: ['Profesor', 'Estudiante', 'Amigo', 'Niño'] },
  { front: 'Dog', back: 'Perro', options: ['Perro', 'Gato', 'Pájaro', 'Caballo'] },
  { front: 'Cat', back: 'Gato', options: ['Vaca', 'Gato', 'Perro', 'Pájaro'] },
  { front: 'Bird', back: 'Pájaro', options: ['Caballo', 'Perro', 'Pájaro', 'Gato'] },
  { front: 'Horse', back: 'Caballo', options: ['Gato', 'Vaca', 'Perro', 'Caballo'] },
  { front: 'Cow', back: 'Vaca', options: ['Vaca', 'Caballo', 'Pájaro', 'Perro'] },
  { front: 'City', back: 'Ciudad', options: ['Calle', 'Ciudad', 'Tienda', 'Casa'] },
  { front: 'Street', back: 'Calle', options: ['Ciudad', 'Tienda', 'Calle', 'Escuela'] },
  { front: 'Store', back: 'Tienda', options: ['Casa', 'Calle', 'Ciudad', 'Tienda'] },
  { front: 'Car', back: 'Coche', options: ['Coche', 'Autobús', 'Tren', 'Bicicleta'] },
  { front: 'Bus', back: 'Autobús', options: ['Tren', 'Autobús', 'Coche', 'Bicicleta'] },
  { front: 'Train', back: 'Tren', options: ['Bicicleta', 'Coche', 'Tren', 'Autobús'] },
  { front: 'Bicycle', back: 'Bicicleta', options: ['Autobús', 'Tren', 'Coche', 'Bicicleta'] },
  { front: 'Sun', back: 'Sol', options: ['Sol', 'Luna', 'Lluvia', 'Día'] },
  { front: 'Moon', back: 'Luna', options: ['Noche', 'Luna', 'Sol', 'Lluvia'] },
  { front: 'Rain', back: 'Lluvia', options: ['Sol', 'Noche', 'Lluvia', 'Día'] },
  { front: 'Day', back: 'Día', options: ['Mañana', 'Noche', 'Luna', 'Día'] },
  { front: 'Night', back: 'Noche', options: ['Noche', 'Día', 'Mañana', 'Sol'] },
  { front: 'Morning', back: 'Mañana', options: ['Día', 'Mañana', 'Noche', 'Luna'] },
  { front: 'Red', back: 'Rojo', options: ['Azul', 'Verde', 'Rojo', 'Amarillo'] },
  { front: 'Blue', back: 'Azul', options: ['Blanco', 'Negro', 'Verde', 'Azul'] },
  { front: 'Green', back: 'Verde', options: ['Verde', 'Rojo', 'Amarillo', 'Azul'] },
  { front: 'Yellow', back: 'Amarillo', options: ['Negro', 'Amarillo', 'Blanco', 'Rojo'] },
  { front: 'White', back: 'Blanco', options: ['Azul', 'Negro', 'Blanco', 'Verde'] },
  { front: 'Black', back: 'Negro', options: ['Rojo', 'Blanco', 'Amarillo', 'Negro'] },
  { front: 'Big', back: 'Grande', options: ['Grande', 'Pequeño', 'Rápido', 'Lento'] },
  { front: 'Small', back: 'Pequeño', options: ['Bueno', 'Pequeño', 'Grande', 'Malo'] },
  { front: 'Good', back: 'Bueno', options: ['Malo', 'Feliz', 'Bueno', 'Triste'] },
  { front: 'Bad', back: 'Malo', options: ['Bueno', 'Grande', 'Pequeño', 'Malo'] },
  { front: 'Happy', back: 'Feliz', options: ['Feliz', 'Triste', 'Bueno', 'Malo'] },
  { front: 'Sad', back: 'Triste', options: ['Rápido', 'Triste', 'Feliz', 'Lento'] },
  { front: 'Fast', back: 'Rápido', options: ['Lento', 'Grande', 'Rápido', 'Pequeño'] },
  { front: 'Slow', back: 'Lento', options: ['Rápido', 'Pequeño', 'Grande', 'Lento'] },
]